#SPDX-License-Identifier: MIT-0
---
# defaults file for roles/terminal
OMZ_DIR: $HOME/.config/omz
EXPORT_OMZ_DIR: ZSH=$HOME/.config/omz
OMZ_CUSTOM: $HOME/.config/omz/custom

ZSH_CUSTOM_FILES: {
  "alias.zsh": "{{ role_path }}/files/zsh/alias.zsh",
  "functions.zsh": "{{ role_path }}/files/zsh/functions.zsh",
}

ZSH_CUSTOM_PLUGINS: {
  "zsh-syntax-highlighting": "https://github.com/zsh-users/zsh-syntax-highlighting.git",
  "zsh-fzf-history-search": "https://github.com/joshskidmore/zsh-fzf-history-search",
}

package_list: [
  bat,
  duf,
  # fd,
  # fx,
  glow,
  lsd,
  ncdu,
  # tldr,
  ranger,
  zoxide,
  zsh,
  fzf,
  git,
  curl,
]

