---
- name: "Install ly display manager"
  ansible.builtin.package:
    name: ly
    state: present
  become: true

- name: "Enable the ly systemd service"
  ansible.builtin.systemd_service:
    name: ly@tty2
    enabled: true
  become: true

- name: "Disable the getty systemd service"
  ansible.builtin.systemd_service:
    name: getty@tty2
    enabled: false
  become: true
